apiVersion: 1

datasources:
  - name: Financial RAG API
    uid: financial-rag-api
    type: yesoreyeram-infinity-datasource
    access: proxy
    url: http://backend:8000
    isDefault: true
    editable: false

  - name: Prometheus
    uid: prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: false
    editable: false

  - name: Tempo
    uid: tempo
    type: tempo
    access: proxy
    url: http://tempo:3200
    isDefault: false
    editable: false
